<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Apigility & Ember.js TodoApi</title>
    <link rel="stylesheet" href="css/bootstrap.css">
    <link rel="stylesheet" href="css/app.css">
</head>
<body>

    <div class="title-container">
        <div class="title">
            <span class="small">Demo</span><br />
            <a href="http://lab.empirio.no/emberjs-say-hello-to-apigility.html">Ember.js say hello to Apigility.</a><br />
            <span class="small"><a href="http://lab.empirio.no/">Flamur Mavraj</a> (<a href="https://twitter.com/oxodesign">@oxodesign</a>)</span>
        </div>
    </div>

    <script type="text/x-handlebars" data-template-name="application">
        <div class="container">
            <h1>Ember.js & Apigility Todo app</h1>

            {{outlet}}
        </div>
    </script>

    <script type="text/x-handlebars" data-template-name="todos">
        <form {{action "add" on="submit"}}>
        {{view Ember.TextField valueBinding="todoName" placeholder="Add a new task" class="form-control"}}<br />
        </form>

        <br /><br />

        <ul class="list-unstyled">
            {{#each}}
            <li {{bind-attr class="isCompleted:text-muted isCompleted:done"}}>
                <button {{action delete this}} class="btn btn-danger btn-danger-round btn-xs">x</button>
                {{view Ember.Checkbox checkedBinding="isCompleted"}} {{name}}
            </li>
            {{/each}}
        </ul>
    </script>

    <script src="javascript/vendor/jquery-1.10.2.js"></script>
    <script src="javascript/vendor/handlebars-v1.3.0.js"></script>
    <script src="javascript/vendor/ember.js"></script>
    <script src="javascript/vendor/ember-data.js"></script>
    <script src="javascript/vendor/bootstrap.js"></script>
    <script src="javascript/app.js"></script>

</body>
</html>
